version: '3.8'

services:
  sdr-ia:
    build: .
    container_name: sdr-ia-nautico
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      # Monta o .env diretamente
      - ./.env:/app/.env:ro
      # Monta logs para persistência
      - ./logs:/app/logs
      # Monta uploads se necessário
      - ./uploads:/app/uploads
    environment:
      # Força algumas variáveis importantes
      - PYTHONUNBUFFERED=1
      - TZ=America/Sao_Paulo
      - FORCE_REBUILD=2025-08-03-v3
    networks:
      - sdr-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Redis OBRIGATÓRIO para follow-ups do Náutico
  redis:
    image: redis:7-alpine
    container_name: sdr-redis-nautico
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - sdr-network
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  sdr-network:
    driver: bridge

volumes:
  redis-data: